version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reelingit
    ports:
      - "5432:5432"
    networks:
      - reelingit-net
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  reelingit-net:
    driver: bridge
